server:
  port: 29980
  servlet:
    context-path: /api
spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/order_db?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml
dubbo:
  application:
    name: demo
  registry:
    address: 127.0.0.1:2181
    default: true